// File generated by FlutterFire CLI, then adjusted to read Firebase options
// from the local .env asset instead of committing API keys to source control.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:tenant_management_app/services/env_config.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: EnvConfig.requireValue('FIREBASE_WEB_API_KEY'),
    appId: EnvConfig.requireValue('FIREBASE_WEB_APP_ID'),
    messagingSenderId: EnvConfig.requireValue(
      'FIREBASE_WEB_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requireValue('FIREBASE_WEB_PROJECT_ID'),
    authDomain: EnvConfig.requireValue('FIREBASE_WEB_AUTH_DOMAIN'),
    storageBucket: EnvConfig.requireValue('FIREBASE_WEB_STORAGE_BUCKET'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvConfig.requireValue('FIREBASE_ANDROID_API_KEY'),
    appId: EnvConfig.requireValue('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: EnvConfig.requireValue(
      'FIREBASE_ANDROID_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requireValue('FIREBASE_ANDROID_PROJECT_ID'),
    storageBucket: EnvConfig.requireValue('FIREBASE_ANDROID_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvConfig.requireValue('FIREBASE_IOS_API_KEY'),
    appId: EnvConfig.requireValue('FIREBASE_IOS_APP_ID'),
    messagingSenderId: EnvConfig.requireValue(
      'FIREBASE_IOS_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requireValue('FIREBASE_IOS_PROJECT_ID'),
    storageBucket: EnvConfig.requireValue('FIREBASE_IOS_STORAGE_BUCKET'),
    iosClientId: EnvConfig.requireValue('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: EnvConfig.requireValue('FIREBASE_IOS_BUNDLE_ID'),
  );
}
