// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️ PLACEHOLDER — Chạy lệnh sau để sinh file thật:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Sau khi chạy, file này sẽ được ghi đè với cấu hình Firebase thật.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ PLACEHOLDER VALUES — Thay bằng giá trị thật từ Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'YOUR-PROJECT-ID.firebaseapp.com',
    storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1jA5C53DpwDICKEWZ8DCvaq_Bd9t_wA',
    appId: '1:804871641062:android:b9789ce0c8bd9519c46827',
    messagingSenderId: '804871641062',
    projectId: 'lumiere-stay',
    storageBucket: 'lumiere-stay.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkJm1HEw6sXuQsYpqcHoQCCoxhNiagoU',
    appId: '1:804871641062:ios:d214e9d8da37c5a9c46827',
    messagingSenderId: '804871641062',
    projectId: 'lumiere-stay',
    storageBucket: 'lumiere-stay.firebasestorage.app',
    iosClientId: '804871641062-nhlikp3fa431eqcvrt9ngmsmondhpcta.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenantManagementApp',
  );
}
